badge_ci:
  enabled: "true"
  settings:
    label_color: "black"
    label: "Build"
    logo: "github"
    color: darkgreen

badge_ticket:
  enabled: "true"
  settings:
    color: "black"
    label: "Issue"
    sed_pattern: '.*\[GH-([0-9]+)\].*'
    url: "https://github.com/aiKrice/badgetizr/issues/%s"
    logo: "github"

badge_base_branch:
  enabled: "false"
  settings:
    color: "orange"
    label: "Base Branch"
    base_branch: "develop"

badge_wip:
  enabled: "true"
  settings:
    color: "yellow"
    label: "WIP"
    logo: "vlcmediaplayer"
    labelized: "Work In Progress"

badge_dynamic:
  enabled: "true"
  settings:
    patterns:
      - badge_1:
        sed_pattern: '(- \[ \] Task 1)'
        label: "Task 1"
        value: "Missing"
        color: "orange"
      - badge_2:
        sed_pattern: '(- \[x\] Task 1)'
        label: "Task 1"
        value: "Completed"
        color: "forestgreen"
      - badge_3:
        sed_pattern: '(- \[x\] Task 2)'
        label: "Task 2"
        value: "Missing"
        color: "orange"
      - badge_4:
        sed_pattern: '(- [ ] Task 2)'
        label: "Task 2"
        value: "Completed"
        color: "forestgreen"
