badge_ci:
  enabled: "true"
  settings:
    label_color: "black"
    label: "Build"
    logo: "github"
    color: darkgreen

badge_ticket:
  enabled: "true"
  settings:
    color: "black"
    label: "Issue"
    sed_pattern: '.*\[GH-([0-9]+)\].*'
    url: "https://github.com/aiKrice/homebrew-badgetizr/issues/%s"
    logo: "github"

badge_base_branch:
  enabled: "true"
  settings:
    color: "orange"
    label: "Base Branch"
    base_branch: "develop"

badge_wip:
  enabled: "true"
  settings:
    color: "yellow"
    label: "WIP"
    logo: "vlcmediaplayer"
    labelized: "Work In Progress"

badge_hotfix:
  enabled: "true"
  settings:
    color: "red"
    text_color: "white"
    label: "HOTFIX"
    labelized: "🔥 Hotfix"

badge_dynamic:
  enabled: "true"
  settings:
    patterns:
      - badge_1:
        sed_pattern: '(- \[ \] The PR starts by)'
        label: "Github Issue"
        value: "Missing"
        color: "orange"
      - badge_2:
        sed_pattern: '(- \[ \] I have added WIP)'
        label: "WIP Test"
        value: "Missing"
        color: "orange"
      - badge_3:
        sed_pattern: '(- \[ \] I have tested on the)'
        label: "GitLab Test"
        value: "Missing"
        color: "orange"

badge_ready_for_approval:
  enabled: "true"
  settings:
    color: "darkgreen"
    label: "Ready"
    logo: "checkmark"
    labelized: "Ready for Approval"
