name: 'Badgetizr'
description: 'Automatically add custom badges to pull requests - boost productivity and streamline code reviews'
branding:
  icon: 'award'
  color: 'green'
inputs:
  pr_id:
    description: 'Specify the path to the configuration. Default is .badgetizr.yml'
    required: true
  configuration:
    description: 'The path to the configuration. Default is .badgetizr.yml'
    required: false
    default: '.badgetizr.yml'
  pr_destination_branch:
    description: '(Mandatory when branch badge is enabled) Specify the pull request destination branch'
    required: false
  pr_build_number:
    description: '(Mandatory when CI badge is enabled) Specify the pull request build number'
    required: false
  pr_build_url:
    description: '(Mandatory when CI badge is enabled) Specify the pull request build url'
    required: false
  ci_status:
    description: '(Mandatory when CI status badge is enabled) CI status: started, passed, warning, failed'
    required: false
  ci_text:
    description: '(Optional) Custom text for CI status badge. Defaults to status value'
    required: false
runs:
  using: 'composite'
  steps:
    - name: Install dependencies
      run: |
        if [[ "$(uname)" == "Darwin" ]]; then
          echo "Running on macOS"
          if ! command -v gh &> /dev/null; then
            echo "GitHub CLI (gh) not found. Installing..."
            brew install gh
          fi

          if ! command -v yq &> /dev/null; then
            echo "yq not found. Installing..."
            brew install yq
          fi
        else
          echo "Running on Linux"
          if ! command -v gh &> /dev/null; then
            echo "GitHub CLI (gh) not found. Installing..."
            sudo apt-get update
            sudo apt-get install -y gh
          fi

          if ! command -v yq &> /dev/null; then
            echo "yq not found. Installing mikefarah/yq..."
            sudo wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
            sudo chmod +x /usr/local/bin/yq
          fi
        fi
      shell: bash
    - name: "Execute Badgetizr"
      run: |
        pr_id="${{ inputs.pr_id }}"
        configuration="${{ inputs.configuration }}"
        pr_destination_branch="${{ inputs.pr_destination_branch }}"
        pr_build_number="${{ inputs.pr_build_number }}"
        pr_build_url="${{ inputs.pr_build_url }}"
        ci_status="${{ inputs.ci_status }}"
        ci_text="${{ inputs.ci_text }}"

        args=("-c" "$configuration")
        if [ -n "$pr_id" ]; then
          args+=("--pr-id=$pr_id")
        fi
        if [ -n "$pr_destination_branch" ]; then
          args+=("--pr-destination-branch" "$pr_destination_branch")
        fi
        if [ -n "$pr_build_number" ]; then
          args+=("--pr-build-number" "$pr_build_number")
        fi
        if [ -n "$pr_build_url" ]; then
          args+=("--pr-build-url" "$pr_build_url")
        fi
        if [ -n "$ci_status" ]; then
          args+=("--ci-status=$ci_status")
        fi
        if [ -n "$ci_text" ]; then
          args+=("--ci-text" "$ci_text")
        fi

        ./badgetizr "${args[@]}"
      shell: bash